version: '3.8'

services:
  backend:
    build: ./back-end
    container_name: laravel_backend
    ports:
      - "8000:80"
    volumes:
      - ./back-end:/var/www/html
    depends_on:
      - db

  frontend:
    build: ./front-end
    container_name: vue_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./front-end:/app
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
